name: Deploy Terraform Infra to Azure

on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        description: 'Environment to Deploy SiteFinity too'
        required: true
        type: environment
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.ENVIRONMENT }} 
    env:
      ARM_CLIENT_ID: ${{vars.ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{vars.ARM_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{vars.ARM_TENANT_ID}}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: infra

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.3
          
      - name: Azure Blob Storage - Download Blob
        uses: armanrahman22/azblob-download-action@v0.0.4
        with:
          storage-account-name: myfilesmwg
          creds: '{"clientId":"${{ vars.ARM_CLIENT_ID }}","clientSecret":"${{ secrets.ARM_CLIENT_SECRET }}","subscriptionId":"${{ vars.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ vars.ARM_TENANT_ID }}"}'
          container-name: sitefinitytfstate
          blob-name: sitefinity.pfx
          download-path: .

      - name: List Files in Directory
        run: ls -R
    
      - name: Terraform Init
        run: terraform init
        working-directory: infra

      - name: Terraform Apply
        run: terraform apply -auto-approve --var-file=${{vars.TFVARS_FILE}} 
        working-directory: infra

      - name: Terraform Output
        run: terraform output
        working-directory: infra
        


       

      
