name: Deploy Terraform Infra to Azure

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{vars.ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{vars.ARM_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{vars.ARM_TENANT_ID}}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: infra

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.3

      - name: List Files in Directory
        run: ls -R
    
      - name: Terraform Init
        run: terraform init
        working-directory: infra

      # - name: Terraform Plan
      #   run: terraform plan --var-file=dev.tfvars
      #   working-directory: infra

      - name: Terraform Apply
        run: terraform apply -auto-approve --var-file=./dev.tfvars
        working-directory: infra

      - name: Terraform Output
        run: terraform output
        working-directory: infra
        


       

      
